server:
  port: 8080

spring:
  application:
    name: order-notification-system-sqs
  cloud:
    aws:
      region:
        static: ap-south-1
      sqs:
        # Uncomment ONLY if running LocalStack locally on port 4566
        # endpoint: http://localhost:4566

app:
  queue:
    order-events: order-events-queue
    order-events-dlq: order-events-dlq